### ISSUE TITLE
Failed to create new KafkaAdminClient

### ISSUE THREAD

**Issue by tsitsihama** [jomariya23156/sales-forecast-mlops-at-scale#4]
Im getting the following error when i try to run the kafka_spark_db_dag    in airflow 

````
Traceback (most recent call last):
  File "/workspaces/sales-forecast-mlops-at-scale/services/airflow/dags/spark_streaming.py", line 110, in <module>
    stream_kafka_to_db()
  File "/workspaces/sales-forecast-mlops-at-scale/services/airflow/dags/spark_streaming.py", line 107, in stream_kafka_to_db
    write_df_to_db(processed_df)
  File "/workspaces/sales-forecast-mlops-at-scale/services/airflow/dags/spark_streaming.py", line 97, in write_df_to_db
    return query.awaitTermination()
  File "/workspaces/sales-forecast-mlops-at-scale/venv/lib/python3.10/site-packages/pyspark/sql/streaming/query.py", line 221, in awaitTermination
    return self._jsq.awaitTermination()
  File "/workspaces/sales-forecast-mlops-at-scale/venv/lib/python3.10/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
  File "/workspaces/sales-forecast-mlops-at-scale/venv/lib/python3.10/site-packages/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.StreamingQueryException: [STREAM_FAILED] Query [id = 568bfb7c-0611-4ed0-9c8c-d5efb7a22068, runId = 54a32339-a883-4985-b4f8-11d1d58f4f0e] terminated with exception: Faile
```d to create new KafkaAdminClient`

**Comment by jomariya23156** [comment]
First of all, after you have started up the system, can you go to `kafka-ui` at port `8800` and check if there are messages publishing to the main topic? 

If no, there are some networking issues. Check the logs of `kafka`,` kafka-ui`, and `data-producer`.

If yes, then can you try to empty the directory `/services/airflow/spark_streaming_checkpoints` and rerun this DAG? I've just noticed that I didn't remove those checkpoint files. They might be the cause.

**Comment by tsitsihama** [comment]
The messages are being published to the main topic and i am able to view the data in the rossman_sales in the database , i have deleted everything in this directory `/services/airflow/spark_streaming_checkpoints` the eror still remains  however i think there are files that are suppose to be generated in the `/services/airflow/spark_streaming_checkpoints` but the folder is remaining the same , maybe its the error

**Comment by jomariya23156** [comment]
I guess it's about the file/directory permission then. If you're suspecting `spark_streaming_checkpoints/` you can disable checkpointing by simply commenting [lines 92-94 ](https://github.com/jomariya23156/sales-forecast-mlops-at-scale/blob/master/services/airflow/dags/spark_streaming.py#L92). It won't affect other parts, except when you rerunning this DAG, it will reread all the messages in the topic instead of where it left off last time. But it's fine for debugging.

**Comment by jomariya23156** [comment]
I'm closing the issue since it seems inactive now. Please feel free to reopen again or open a new one if you have more problems.
